### GET Root
GET http://localhost:3000/

### CREATE PERSON

POST http://localhost:3000/person/
Content-Type: application/json

{
	"name": "Peter Robinson",
	"age": 31
}

### GET ALL PEOPLE
GET http://localhost:3000/person