### GET Root
GET http://localhost:3000/

### CREATE PERSON

POST http://localhost:3000/person/
Content-Type: application/json

{
	"name": "George Lopez",
	"age": 54
}

### FIND ALL PEOPLE
GET http://localhost:3000/people/

### FIND A PERSON By NAME 
GET http://localhost:3000/person